### ISSUE TITLE
MySQL Compatibility ?

### ISSUE THREAD

**Issue by Frinn38** [PotatoSauceVFX/Whitelist-Sync#3]
This is an awesome mod which can be very helpful.

However the fact it use sqlite db is very limiting because if, like in my case, the servers are isolated in differents containers and can't acces to an unique whitelist.db

So is it possible to adapt this mod to work with an mysql database ? that would be greatfull =)

**Comment by rmnaderdev** [comment]
Yeah, I think I can integrate that. I am a very busy person so I'll try to work on it asap.

**Comment by rmnaderdev** [comment]
I honestly didn't think many people would use this so we didn't add mySQL integration but I would like to mess with it.

**Comment by Frinn38** [comment]
Thanks for the reply, I hope you'll be able to find the time to integrate mysql support on this.

**Comment by rmnaderdev** [comment]
I have started implementing JDBC to Whitelist sync. Update should come out soon.

**Comment by Frinn38** [comment]
Nice work, thank you =D

**Comment by rmnaderdev** [comment]
https://github.com/PotatoSauceVFX/WhitelistSyncRewrite Decided to rewrite it. It was quite messy.

**Comment by rmnaderdev** [comment]
Just posted the new releases. The mod now supports MYSQL! Don't forget the extra dependency.
[Download Here!](https://minecraft.curseforge.com/projects/whitelist-sync) If you have any troubles open a issue on [HERE](https://github.com/PotatoSauceVFX/WhitelistSyncRewrite)

**Comment by Frinn38** [comment]
Thank you for all your work. That's awesome ! =)

**Comment by rmnaderdev** [comment]
No problem! ;)
